- name: Install and Ensure Zabbix Agent is Running
  hosts: all
  become: true
  tasks:

    - name: Install Zabbix Agent (Debian/Ubuntu)
      ansible.builtin.apt:
        name: zabbix-agent
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Check if Zabbix Agent is installed
      ansible.builtin.command: systemctl status zabbix-agent
      register: zabbix_status
      ignore_errors: true
      changed_when: false

    - name: Enable and Start Zabbix Agent
      ansible.builtin.systemd:
        name: zabbix-agent
        state: started
        enabled: yes
      when: zabbix_status.rc != 0
